#pragma once
#include "RobotBase.h"

RobotThread skillsAuton();
RobotThread blueRingSide();
RobotThread blueRingRush();
RobotThread blueMogoSide();
RobotThread blueMogoRush();
RobotThread blueSAWP();
RobotThread redRingSide();
RobotThread redRingRush();
RobotThread redMogoSide();
RobotThread redMogoRush();
RobotThread redMogoFake();
RobotThread redSAWP();
RobotThread sbhsRedMogoSide();
RobotThread sbhsBlueMogoSide();
RobotThread sbhsRedRingSide();
RobotThread sbhsBlueRingSide();